# Generated by Django 4.1.7 on 2023-03-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0004_venue_rename_registration_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
