# Generated by Django 4.1.1 on 2023-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0005_event_description_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='heading',
            field=models.CharField(default='tressure hunt', max_length=50),
        ),
    ]
