# Generated by Django 4.1.1 on 2023-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0007_event_photo_student_college_student_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=100, verbose_name='college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='events',
            field=models.CharField(max_length=100, verbose_name='events'),
        ),
    ]
