# Generated by Django 4.1.1 on 2023-04-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0009_remove_student_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ignite.event'),
        ),
    ]
