# Generated by Django 4.1.1 on 2023-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0010_student_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.ImageField(upload_to='images'),
        ),
    ]
