# Generated by Django 4.1.7 on 2023-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0012_select_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select_event',
            name='rate',
        ),
        migrations.AddField(
            model_name='select_event',
            name='event_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
