# Generated by Django 4.1.7 on 2023-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0013_remove_select_event_rate_select_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
