# Generated by Django 4.1.1 on 2023-05-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0016_alter_event_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ignite.event'),
        ),
    ]
