# Generated by Django 4.1.1 on 2023-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0018_alter_result_candidate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_id',
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='block A', max_length=30, verbose_name='venue_name'),
        ),
    ]
