# Generated by Django 4.1.1 on 2023-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0020_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=30, null=True, verbose_name='status'),
        ),
    ]
