# Generated by Django 4.1.1 on 2023-05-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0021_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
