# Generated by Django 4.1.1 on 2023-05-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0024_remove_result_pgm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='event',
            new_name='event_id',
        ),
    ]
