# Generated by Django 4.1.1 on 2023-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0025_rename_event_judge_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='events',
        ),
        migrations.AddField(
            model_name='student',
            name='events',
            field=models.ManyToManyField(blank=True, to='ignite.event'),
        ),
    ]
