# Generated by Django 4.1.1 on 2023-05-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0026_remove_student_events_student_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='event_id',
            new_name='event',
        ),
    ]
