# Generated by Django 4.1.1 on 2023-05-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0027_rename_event_id_judge_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='select_event',
        ),
    ]
