# Generated by Django 4.1.1 on 2023-05-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0028_delete_select_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
