# Generated by Django 4.1.1 on 2023-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0029_remove_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='qualification',
            field=models.CharField(max_length=25, verbose_name='Qualification'),
        ),
    ]
