# Generated by Django 4.1.1 on 2023-05-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ignite', '0031_notification_delete_accomodation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
